export * from './clone'
export * from './compose'
export * from './curry'
export * from './debounce'
export * from './generator'
export * from './M'
export * from './memorize'
export * from './myBind'
export * from './myCall'
export * from './myInstanceOf'
export * from './myNew'
export * from './myApply'
export * from './patial'
export * from './throttle'

