export * from './checkCarCard'
export * from './checkColor'
export * from './checkDate'
export * from './checkMail'
export * from './checkPhoneNumber'
export * from './regTpl'
export * from './trimSpace'